### ISSUE TITLE
error: instruction requires: el3

### ISSUE THREAD

**Issue by xiaoniaoyouhuajiang** [aengelke/instrew#11] opened 2024-01-05 15:51 UTC
I have cloned this repository and  successfully executed 'meson build-Dbuildtype =release', when I executed `ninja -C build` to compiling，something went wrong like this:

```shell
FAILED: subprojects/rellume/tests/parsed_cases_aarch64.txt 
/usr/bin/python3 ../subprojects/rellume/tests/test_parser.py -o subprojects/rellume/tests/parsed_cases_aarch64.txt -a /home/xiao-sa/software/instrew/build/subprojects/rellume/tests/test_assembler -A aarch64 ../subprojects/rellume/tests/a64_data_proc.txt ../subprojects/rellume/tests/a64_loads_stores.txt ../subprojects/rellume/tests/a64_branches_and_cond.txt ../subprojects/rellume/tests/a64_scalar_fp.txt ../subprojects/rellume/tests/a64_simd.txt
error: instruction requires: el3
 smc #0
 ^
error parsing line 4 non-hexadecimal number found in fromhex() arg at position 0
Traceback (most recent call last):
  File "/home/xiao-sa/software/instrew/build/../subprojects/rellume/tests/test_parser.py", line 96, in <module>
    raise e
  File "/home/xiao-sa/software/instrew/build/../subprojects/rellume/tests/test_parser.py", line 90, in <module>
    case = parse_case(line, asm)
  File "/home/xiao-sa/software/instrew/build/../subprojects/rellume/tests/test_parser.py", line 56, in parse_case
    code, term = asm.assemble(val)
  File "/home/xiao-sa/software/instrew/build/../subprojects/rellume/tests/test_parser.py", line 25, in assemble
    res = bytes.fromhex(self.proc.stdout.readline().strip())
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```
My personal PC is **x86-64** system, does the error mean missing arm64 instruction? How should I solve this problem

**Comment by aengelke** [comment] 2024-01-05 16:08
Which LLVM version? It works for me:

```
$ echo "!ASM smc #0" | ./subprojects/rellume/tests/test_assembler aarch64
030000d4
$ llvm-config --version
17.0.4
$ uname -m
x86_64
```

**Comment by xiaoniaoyouhuajiang** [comment] 2024-01-05 16:23
My system configuration is as follows, do I need to change the llvm version or try something else

```shell
$ echo "!ASM smc #0" | ./subprojects/rellume/tests/test_assembler aarch64
bash: !ASM: event not found
$ llvm-config-14 --version
14.0.0
$ uname -m
x86_64
```

**Comment by xiaoniaoyouhuajiang** [comment] 2024-01-05 16:23
> Which LLVM version? It works for me:
> 
> ```
> $ echo "!ASM smc #0" | ./subprojects/rellume/tests/test_assembler aarch64
> 030000d4
> $ llvm-config --version
> 17.0.4
> $ uname -m
> x86_64
> ```

My system configuration is as follows, do I need to change the llvm version or try something else

```shell
$ echo "!ASM smc #0" | ./subprojects/rellume/tests/test_assembler aarch64
bash: !ASM: event not found
$ llvm-config-14 --version
14.0.0
$ uname -m
x86_64
```

**Comment by aengelke** [comment] 2024-01-05 16:53
I just did a [test build with LLVM 14](https://builds.sr.ht/~aengelke/job/1127811), it worked fine.

Re the first command I gave: use `echo '!ASM smc #0' | ./subprojects/rellume/tests/test_assembler aarch64` (single quotes instead of double quotes), sorry about that.

**Comment by xiaoniaoyouhuajiang** [comment] 2024-01-14 02:29
> I just did a [test build with LLVM 14](https://builds.sr.ht/~aengelke/job/1127811), it worked fine.
> 
> Re the first command I gave: use `echo '!ASM smc #0' | ./subprojects/rellume/tests/test_assembler aarch64` (single quotes instead of double quotes), sorry about that.

I tried this and recived "No such file", is test_assembler something i need to compiler for the subproject? It seems instrew depend on the subproject `rellume`,so I cloned rellume alone and try to build, but it remind me that I can't get the subproject named `frvdec`

**Comment by orangecms** [comment] 2024-03-24 11:19
> > I just did a [test build with LLVM 14](https://builds.sr.ht/~aengelke/job/1127811), it worked fine.
> > Re the first command I gave: use `echo '!ASM smc #0' | ./subprojects/rellume/tests/test_assembler aarch64` (single quotes instead of double quotes), sorry about that.
> 
> I tried this and recived "No such file", is test_assembler something i need to compiler for the subproject? It seems instrew depend on the subproject `rellume`,so I cloned rellume alone and try to build, but it remind me that I can't get the subproject named `frvdec`

You need to clone the repo recursively, or otherwise add the submodules later.
Look for help on "git submodules". :-)

**Comment by aengelke** [comment] 2024-06-07 13:24
Closing as I still can't reproduce this.

**Closed as not planned by aengelke** 2024-06-07 13:24 UTC
